server:
  port: 8082

cors:
  rules:
    - path: "/*"
      allowed_origins:
        - "*"

mysql:
  dsn: "gotester:test123@tcp(127.0.0.1:3306)/gotest?parseTime=true"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 1800 # 30 minutes
