repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: Run golangci-lint
        entry: golangci-lint run ./...
        language: system
        pass_filenames: false

      - id: go-test
        name: Run go test
        entry: go test ./...
        language: system
        pass_filenames: false
