repos:
  - repo: local
    hooks:
      - id: lint
        name: Run make lint
        entry: make lint
        language: system
        pass_filenames: false

      - id: test
        name: Run make test
        entry: make test
        language: system
        pass_filenames: false
