repos:
  - repo: local
    hooks:
      - id: fmt
        name: Run make fmt
        entry: make fmt
        language: system
        pass_filenames: false

      - id: lint
        name: Run make lint
        entry: make lint
        language: system
        pass_filenames: false

      - id: unit-test
        name: Run make unit-test
        entry: make unit-test
        language: system
        pass_filenames: false
