{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monorepo.fullname" $ }}-{{ $name }}
  labels:
    app.kubernetes.io/name: {{ include "monorepo.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
spec:
  replicas: {{ $svc.replicaCount | default ($.Values.global.replicaCount | default 1) }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          imagePullPolicy: {{ $svc.image.pullPolicy | default ($.Values.global.image.pullPolicy | default "IfNotPresent") }}

          ports:
            - name: http
              containerPort: {{ $svc.service.ports.http.targetPort | default 8080 }}
            - name: grpc
              containerPort: {{ $svc.service.ports.grpc.targetPort | default 9090 }}

          env:
            {{- range $k, $v := ($svc.env | default dict) }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}

            {{- range $i, $call := ($svc.calls | default list) }}
            {{- $target := index $.Values.services $call.name }}
            {{- $host := printf "%s-%s" (include "monorepo.fullname" $) $call.name }}
            {{- $val := "" }}

            {{- if eq $call.protocol "http" }}
            {{- $p := int ($target.service.ports.http.port | default 8080) }}
            {{- $val = printf "http://%s:%d" $host $p }}

            {{- else if eq $call.protocol "grpc" }}
            {{- $p := int ($target.service.ports.grpc.port | default 9090) }}
            {{- $val = printf "%s:%d" $host $p }}

            {{- else }}
            {{- fail (printf "unsupported call protocol '%s' in services.%s.calls" $call.protocol $name) }}
            {{- end }}

            - name: {{ include "monorepo.callEnvKey" (dict "svc" $call.name "proto" $call.protocol) }}
              value: {{ $val | quote }}
            {{- end }}

          {{- if $svc.secretEnv }}
          envFrom:
            - secretRef:
                name: {{ include "monorepo.fullname" $ }}-{{ $name }}
          {{- end }}

          resources:
{{- toYaml ($svc.resources | default $.Values.global.resources) | nindent 12 }}
---
{{- end }}
