{{- range $name, $svc := .Values.services }}
{{- if $svc.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monorepo.fullname" $ }}-{{ $name }}
type: Opaque
stringData:
{{- range $key, $value := $svc.secretEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{- end }}
{{- end }}
