{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monorepo.fullname" $ }}-{{ $name }}
  labels:
    app.kubernetes.io/name: {{ include "monorepo.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: {{ $svc.service.type | default ($.Values.global.service.type | default "ClusterIP") }}
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.service.ports.http.port | default 80 }}
      targetPort: http
      {{- if eq ($svc.service.type | default "ClusterIP") "NodePort" }}
      nodePort: {{ $svc.service.nodePorts.http | default 30080 }}
      {{- end }}
      protocol: TCP
    - name: grpc
      port: {{ $svc.service.ports.grpc.port | default 9090 }}
      targetPort: grpc
      protocol: TCP
---
{{- end }}
