server:
  port: 8081

cors:
  rules:
    - path: "/v1/*"
      allowed_origins:
        - "*"

mysql:
  dsn: "auth:authpass@tcp(mysql:3306)/auth?parseTime=true"

redis:
  addr: "localhost:6379"
  password: "test123"
  db: 0

# generate a random secret key for JWT
# 32 bytes base64
#openssl rand -base64 32
# or hex:
#openssl rand -hex 32
jwt:
  secret: "L8hCW84Q5XiY2Z3aDT28UN1f3uUSgfcQdWlxy3GsB8Q="
  expire: 60 # minutes

refresh:
  num_bytes: 32
  end_point: "/refresh"
  max_age: 2592000 # 30 days