services:
  auth:
    secretEnv:
      AUTH_JWT_SECRET: "L8hCW84Q5XiY2Z3aDT28UN1f3uUSgfcQdWlxy3GsB8Q="
      AUTH_REDIS_PASSWORD: "test123"
  user:
    secretEnv:
      USER_MYSQL_PASSWORD: "test123"
